language: php
php:
- 5.4
mysql:
  database: lift
  username: root
  encoding: utf8
addons:
  artifacts: true
before_install:
- wget https://raw.githubusercontent.com/jonkemp/qunit-phantomjs-runner/master/runner.js
install:
- mysql -e 'create database lift;'
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer global require --no-interaction --prefer-source drush/drush:6.*@dev
- mv acquia_lift.make.dev.example acquia_lift.dev.make
- ls
- drush make acquia_lift.dev.make -y
- ls
- pwd
- cd behat-tests
- composer install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
- cd ..
- wget --no-verbose http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
- java -jar selenium-server-standalone-2.45.0.jar&
- echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
- drush si --db-url=mysql://root:@127.0.0.1/lift --account-name=admin --account-pass=admin
  --account-mail=admin@test.com --site-mail=noreply@test.com --site-name="lift" --yes
- drush en acquia_lift -y
- drush dis overlay -y
- drush php-eval "variable_set('acquia_lift_account_info', array('owner_code' => 'owner_eheBBPJME',
  'api_key' => 'api-aiyxahhDMKkWmdJZkpVrHbZF', 'admin_key' => 'admin-VNVOIkwpUwnTMykRBICvpFxQjq',
  'api_url' => 'api-us1.lift.acquia.com'));"
- cd behat-tests
- mv behat.template.yml behat.yml
- sed -i -- 's#localurl#localhost:8080/lift#g' behat.yml
- sed -i -- 's#/Path/to/Drual/Webroot#/home/travis/build/acquia/acquia_lift#g' behat.yml
- cd ..
- BUILD_OWNER=`dirname $TRAVIS_BUILD_DIR`
- echo $BUILD_OWNER
script:
- phantomjs runner.js qunit/core_personalization.html
- phantomjs runner.js acquia_lift_profiles/qunit/test.html
- phantomjs runner.js qunit/acquia_lift_target.html
- phantomjs runner.js qunit/administration.html
- cd behat-tests
- "./bin/behat"
notifications:
  slack:
    secure: mpS7oDoOBsl7KlQUY9loYd1gUiozp4D8kc3vl0nVkm8N8SpAR0RYplPHY/5Jtesbl73kWG4vV7UURNct0cc+szm0eLVbCFcS6vq6evzPKdHzl0U2YiFCLsJItDXBYhDDb5bY4yZgCY8zUBmnOM/S3NysxMMcNmU/DaqUvhZWnGU=
env:
  global:
  - secure: kIUn8ve9kUZewkspipjbi8HGJaBDD7dQzoiArJkaMX89iLLtKjR6McAYi4XU93uqSqfgvrAE2x8bGjD656w8cZtfwQqpo7R7IzzzdHPAAaW0U0lBIub5ovFnZeY+VbEnKZpl0tl4t3SdMTMrIEhVzhxYx9Iz7S6SScvGi+5rN3c=
  - secure: FwSaG/+UFx7t0ydMCxk57wLu79tPN49LQkqH/oYVKiD2HirF3uqlpIaVKnT7zeQAfMPXA7gTuB54hkKIHtOlxharXZurcWoHRDid6u5ZZj5d/enIoplX1f4yn6EKBRK6HL98V+nQPYX0vjcM9JnPIbuVoj0013jA4x23Dba3eGI=
  - secure: cKmr4fguH2te2n9PaKBFzaDiSvRiy/7OvfpTMPvYOTeW0omNsEEBJypIJQtDeN1ydDRzNkuviFNNzEaXbdLYYyY66LACQyI3vR7BbrYp6lVZDunyKFB6zyXWmIgPM4xSgUz0gnzGI7D6NPbwRnQfRJ06M07uzA4HK5Q//WJkbhs=
